# docker compose build een data_serial
# docker compose --profile een --profile data_serial up
services:
  mqtt:
    image : eclipse-mosquitto:2.0.19
    ports :
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.config:/mosquitto/config/mosquitto.conf
  een:
    image: een
    build:
      context: een
      dockerfile: Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"
    entrypoint: ./app -cMQTT -ahost.docker.internal -spba192.168.130.51
    depends_on:
      - mqtt
    profiles:
      - een
  data_serial:
    image:  data_serial
    build:
      context: data_serial
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    extra_hosts:
    - "host.docker.internal:host-gateway"
    profiles:
      - data_serial
    entrypoint: ./app -cMQTT -ahost.docker.internal
    privileged: true
    volumes:
      - /dev:/dev
