services:
  spbd:
    image: spbd
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    depends_on:
      - mqtt
  mqtt:
    image : eclipse-mosquitto:2.0.19
    ports :
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.config:/mosquitto/config/mosquitto.conf
  spbd_listener:
    image: spbd_listener
    build:
      context: spbd_listener
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"