# sudo docker compose build pub sub
# sudo docker compose --profile pub --profile sub up
services:
  pub:
    image: pub
    build:
      context: pub
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    depends_on:
      - mqtt
    profiles:
      - pub
  mqtt:
    image : eclipse-mosquitto:2.0.19
    ports :
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.config:/mosquitto/config/mosquitto.conf
  sub:
    image: sub
    build:
      context: sub
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    profiles:
      - sub