services:
  spbd:
    image: spbd
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
  mqtt:
    image : eclipse-mosquitto:2.0.19
    ports :
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.config:/mosquitto/config/mosquitto.conf
