# sudo docker compose build pub sub
# sudo docker compose --profile pub --profile sub up
services:
  mqtt:
    image : eclipse-mosquitto:2.0.19
    ports :
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.config:/mosquitto/config/mosquitto.conf
  pub:
    image: pub
    build:
      context: pub
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    depends_on:
      - mqtt
    profiles:
      - pub
  sub:
    image: sub
    build:
      context: sub
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    profiles:
      - sub
  data_b:
    image: data_b
    build:
      context: data_b
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    profiles:
      - data_b
  filter_sample:
    image: filter_sample
    build:
      context: filter_sample
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    profiles:
      - filter_sample
  data_serial:
    image:  data_serial
    build:
      context: data_serial
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      MQ_HOST : "host.docker.internal"
    profiles:
      - data_serial